/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#d3d0cf",
        "surface-bright": "#2c3a4c",
        "on-surface": "#d4e4fa",
        "secondary-fixed-dim": "#b0c6ff",
        "on-secondary-fixed-variant": "#00429b",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#0d1c2d",
        "inverse-on-surface": "#233143",
        "surface-container-highest": "#273647",
        "on-tertiary": "#313030",
        "primary-fixed-dim": "#00daf3",
        "on-primary-fixed": "#001f24",
        "background": "#051424",
        "outline-variant": "#3b494c",
        "primary": "#c3f5ff",
        "secondary": "#b0c6ff",
        "on-tertiary-fixed-variant": "#474646",
        "surface": "#051424",
        "primary-fixed": "#9cf0ff",
        "on-secondary": "#002d6e",
        "on-tertiary-container": "#5a5959",
        "surface-tint": "#00daf3",
        "secondary-fixed": "#d9e2ff",
        "inverse-surface": "#d4e4fa",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-container": "#f2f3ff",
        "tertiary": "#f0ecec",
        "primary-container": "#00e5ff",
        "secondary-container": "#0068ed",
        "surface-container-high": "#1c2b3c",
        "on-error": "#690005",
        "surface-container-lowest": "#010f1f",
        "error-container": "#93000a",
        "on-background": "#d4e4fa",
        "on-primary": "#00363d",
        "on-secondary-fixed": "#001945",
        "error": "#ffb4ab",
        "inverse-primary": "#006875",
        "surface-container": "#122131",
        "surface-variant": "#273647",
        "surface-dim": "#051424",
        "on-primary-fixed-variant": "#004f58",
        "tertiary-fixed-dim": "#c9c6c5",
        "outline": "#849396",
        "on-primary-container": "#00626e",
        "on-tertiary-fixed": "#1c1b1b",
        "on-surface-variant": "#bac9cc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1200px",
        "section-gap": "120px",
        "stack-md": "16px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        unit: "8px",
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "display-lg-mobile": ["Geist"],
        "body-lg": ["Inter"],
        "display-lg": ["Geist"],
        "body-md": ["Inter"],
        "headline-md": ["Geist"],
        "code-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}